// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfxntunkuchzicizuufg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmeG50dW5rdWNoemljaXp1dWZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1Njk5NjcsImV4cCI6MjA2MjE0NTk2N30.KVkFV2LT7Srvn99il2wrW2Yi53KwtsXrHsceT2OXzvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);